### ISSUE TITLE
EnumerableUtils is not resolving

### ISSUE THREAD

**Issue by DougPuchalski** [patricklx/ember-cli-reduce-computed#2]
https://github.com/patricklx/ember-cli-reduce-computed/blob/master/addon/reduced-computed/dependent_array_observer.js#L6

I'm getting `Uncaught TypeError: Cannot read property 'forEach' of undefined` on this line...EnumerableUtils is not resolving, any idea why?

Also, your install docs are a bit vague, where should the import/install be placed in "the app"?

**Comment by Kilowhisky** [comment]
Looks like EnumerableUtils was removed https://github.com/emberjs/ember.js/blob/1a2cd166a86219717a0cde1df4dab497d8dda3e3/CHANGELOG.md

Because why not............ /sarcasm

**Comment by patricklx** [comment]
thanks for the pull request.
mmm, true. it's a bit vague :)
the code to install this should be called before any access  to Ember.computed.\*   

still vague :)
it can be put anywhere, but the app index file would be the best, or an initializer.
